import Providers from "@/components/providers/provider";
import type { Metadata } from "next";
import { Roboto_Slab } from "next/font/google";
import "./globals.css";

const inter = Roboto_Slab({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Hamza Tariq",
  // description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html suppressHydrationWarning={true} lang="en" className={inter.className}>
      <body className="min-h-[100vh]">
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
